
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD_USER}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring-app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD_USER}
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    depends_on:
      - db

volumes:
  db-data: